TEXT <- scan(file="03_WhatIsR.txt", what="char", quote=NULL, sep="")
head(TEXT)
Freq.TEXT <- table(TEXT)
head(Freq.TEXT)
str(Freq.TEXT)
length(Freq.TEXT)
Freq.TEXT<- sort(table(TEXT),decreasing = T)
head(unname(Freq.TEXT))
head(as.vector(Freq.TEXT))
all(unname(Freq.TEXT) == as.vector(Freq.TEXT))
