TEXT <- scan(file="howtostartastartup.txt", what="char", quote=NULL, sep="")
str(TEXT)
head(TEXT)
TEXTtable <- table(TEXT)
str(TEXTtable)
attributes(TEXTtable)
head(TEXTtable)
TEXTDF <- data.frame(TEXTtable)
str(TEXTDF)
head(TEXTDF)
TEXTDF <- data.frame(row.names=TEXTDF$TEXT, Freq=TEXTDF$Freq, Rel.Freq=TEXTDF$Freq/sum(TEXTDF$Freq))
str(TEXTDF)
head(TEXTDF)
orderedTEXTDF <- TEXTDF[order(-TEXTDF$Freq, -rank(rownames(TEXTDF))), ]
str(orderedTEXTDF)
head(orderedTEXTDF)
write.table(orderedTEXTDF, file="howtostartastartup_analyzed_ver1.0.txt",sep="\t", quote=F, col.names=NA)
Data <- read.delim(file="howtostartastartup_analyzed_ver1.0.txt", sep="\t", header=T, row.names = 1, quote=NULL)
str(Data)
head(Data)
