TEXT <- scan(file="howtostartastartup.txt",what="char",quote=NULL)
cat(TEXT, file="howto_vector_ver1.0.txt",sep="\n")
TableTEXT <- table(TEXT)
head(TableTEXT)
SortedTableTEXT <- sort(TableTEXT, decreasing = T)
head(SortedTableTEXT)
head(names(SortedTableTEXT))
str(names(SortedTableTEXT))
NamesSorted <- names(SortedTableTEXT)
str(NamesSorted)
head(unname(SortedTableTEXT))
#TEXTDF <- data.frame(row.names=NamesSorted,unname(SortedTableTEXT))
TEXTDF <- data.frame(SortedTableTEXT)
TEXTDF <- data.frame(row.names=TEXTDF$TEXT, Freq=TEXTDF$Freq, Rel.Freq=TEXTDF$Freq/sum(TEXTDF$Freq))
head(TEXTDF)
head(TEXTDF[order(rownames(TEXTDF),decreasing=T),])
write.table(TEXTDF, file="howtostartastartup_analyzed_ver1.1.txt", sep="\t", quote=F, col.names = NA)
Data <- read.delim(file="howtostartastartup_analyzed_ver1.1.txt", sep="\t", header=T, row.names=1, quote=NULL)
head(Data)
