TEXT <- scan(file="howtostartastartup.txt", what="char", quote=NULL)
head(TEXT)
rep(TEXT)
rep(head(TEXT),2)
SortedTEXT <- sort(TEXT)
CleanedTEXT <- gsub("[[:punct:]]","",SortedTEXT)
head(CleanedTEXT)
table(CleanedTEXT)
sortedTable <- sort(table(CleanedTEXT), decreasing=T)
DataFrame <- data.frame(sortedTable)
head(DataFrame)
DataFrame <- data.frame(row.names = DataFrame$CleanedTEXT, Freq=DataFrame$Freq, Rel.Freq=round(DataFrame$Freq/sum(DataFrame$Freq),3))
head(DataFrame)
write.table(DataFrame, file="20171021_practice", quote = F, col.names = NA, sep="\t")
